# Generated by Django 4.2.3 on 2023-07-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='connection',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='how_meet',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
