# Generated by Django 4.2.3 on 2023-07-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_project_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='immediate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='connection',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
