# Generated by Django 4.2.3 on 2023-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_project_immediate_alter_project_connection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='check_date',
            field=models.CharField(default='', max_length=512),
        ),
    ]
