# Generated by Django 4.2.3 on 2023-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_project_check_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registered_date',
            field=models.CharField(default='', max_length=32),
        ),
    ]
