# Generated by Django 4.2.3 on 2023-07-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_project_registered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registered_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
