# Generated by Django 4.2.3 on 2023-07-21 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_project_check_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='registered_date',
            new_name='first_date',
        ),
    ]
