# Generated by Django 4.2.3 on 2023-07-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_rename_immediate_project_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='employee_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='employer_sms',
            field=models.BooleanField(default=False),
        ),
    ]
