# Generated by Django 4.2.3 on 2023-07-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_project_employee_sms_project_employer_sms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='floor',
            field=models.CharField(default=1, max_length=64),
        ),
    ]
